name: Install Just
description: Installs the Just CLI tool
runs:
  using: composite
  steps:
    - name: Install Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python3 scripts/secure_download.py https://github.com/casey/just/releases/download/1.1.1/just-1.1.1-x86_64-pc-windows-msvc.zip 446e6091b2aa2b40bc57857f1104cfe4153e757379141ae5ded1dec3da59c10b just.zip
        Expand-Archive -Path just.zip -DestinationPath c:/temp
        Move-Item c:/temp/just.exe c:/Windows/just.exe
